---
title: "MARS"
output: html_document
---

---
title: "mars"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# Constructor
new_mars.control = function(x = list()) {
  structure(x,class = "mars.control")
}
```

```{r}
# Validator
validator_mars.control = function(Mmax = 2L,d = 3,trace=FALSE) {
  stopifnot(((Mmax %% 2) == 0) & (Mmax >= 2)) 
  stopifnot(is.numeric(d))
  stopifnot(is.logical(trace))
}
```


```{r}
# helper
mars.control = function(Mmax = 2,d = 3,trace=FALSE) {
  Mmax = as.integer(Mmax)
  if(Mmax %% 2==1 | Mmax < 2 | is.integer(Mmax) == FALSE){
    warning("Mmax needs to be an even integer that is greater than or equal 2")
  }
  validator_mars.control(Mmax)
  new_mars.control(list(Mmax=Mmax,d=d,trace=trace))
}
mc = mars.control()
```




```{r}
# Data
set.seed(123); n <- 10
data <- data.frame(x1=rnorm(n),x2=rnorm(n),y=rnorm(n))
formula <- formula(y ~.)
cc <- match.call() # save the call
mf <- model.frame(formula,data)
y <- model.response(mf)
mt <- attr(mf, "terms")
x <- model.matrix(mt, mf)
x = x[,-1]


```

```{r}
# Hinge function
h <- function(s,x,t) { 
  return(pmax(0,s*(x-t)))
}
```


```{r}
# B and Bfunc
init_B <- function(N,Mmax) {
  B <- data.frame(matrix(NA,nrow=N,ncol=Mmax+1))
  B[,1] <- 1
  names(B) <- c("B0",paste0("B",1:Mmax))
  return(B)
}
```


```{r}
split_points = function(pred,basis){
  vec = pred[basis > 0]
  sort_vec = sort(unique(vec))
  output = sort_vec[-length(sort_vec)]
  return(output)
}



LOF_fwd <- function(form,data) {
  ff <- lm(form,data)
  return(sum(residuals(ff)^2))
}
# test LOF BWD
LOF_bwd = function(formula,data,control) {
  ff = lm(formula,data) # linear model
  RSS = sum(residuals(ff)^2) # Error sum of squares
  N = nrow(data)
  M = length(coefficients(ff)) - 1 
  CM = sum(diag(hatvalues(ff)))
  CM_Tidle = CM + (control$d*M)
  GCV = (RSS*(N/(N-CM_Tidle)^2))
  return(GCV)
}
```


```{r}
fwd_stepwise <- function(y,x,mc){ # Mmax basis matrix
  Mmax = mc$Mmax
  # Initialize:
  N <- length(y) # sample size
  n <- ncol(x) # number of predictors
  B <- init_B(N,mc$Mmax) # Exercise: write init_B() 
  Bfunc = vector(mode = "list",length=mc$Mmax+1) # replace this splits with bfunc which is an empty list (lab5)
  
  #---------------------------------------------------
  # Looping for forward selection:
  for(i in 1:(Mmax/2)) { # Mmax / 2 
    M = ((2*i)-1) # if i = 1 M = 1 , 2    i = 2 M = 3,4  
    lof_best <- Inf
    for(m in 1:M){
      NN <- setdiff(c(1:ncol(x)),Bfunc[[m]][,2])
      
      for(v in NN){ # select a variable to split on
        
        tt <- split_points(x[,v],B[,m]) # Exercise: write split_points() 
        
        for(t in tt) { 
          Bnew <- data.frame(B[,(1:M)[-m]],
                             Btem1=B[,m]*h(1,x[,v],t),Btem2=B[,m]*h(-1,x[,v],t))
          gdat <- data.frame(y=y,Bnew)
          lof <- LOF_bwd(y~.,gdat,mc) #  Use your LOF() from week 4
          if(lof < lof_best) { 
            lof_best <- lof
            #print(lof_best)
            temp_B <- c(m,v,t)
            # replace this as well (lab5)
            #print(Bfunc[[M]])
          } # end if
        } # end loop over splits
      } # end loop over variables
    } # end loop over basis functions to split
    m <- temp_B[1]; v <- temp_B[2]; t <- temp_B[3]
    B[,M+1] <- B[,m]*h(-1,x[,v],t)
    Bfunc[[M+1]] = rbind(Bfunc[[m]],c(s=-1,v=v,t=t)) # copy everthing from left
    
    B[,M+2] <- B[,m]*h(1,x[,v],t) 
    Bfunc[[M+2]] = rbind(Bfunc[[m]],c(s=1,v=v,t=t)) # copy everything from right 
    
  } # end loop over M
  colnames(B) <- paste0("B",(0:(ncol(B)-1)))
  return(list(y=y,B=B,Bfuncs=Bfunc))
}

```


```{r}
fwd_stepwise(y,x,mc)
```




